services:
    menu.search_filter:
        parent: api_platform.doctrine.orm.search_filter
        arguments: [ { type: exact } ]
        tags: [ api_platform.filter ]
        autowire: false
        autoconfigure: false
        public: false

