services:
    created_at.order_filter:
        parent: api_platform.doctrine.orm.order_filter
        arguments: [ { createdAt: ~ } ]
        tags: [ api_platform.filter ]
        autowire: false
        autoconfigure: false
        public: false

    position.order_filter:
        parent: api_platform.doctrine.orm.order_filter
        arguments: [ { position: ~ } ]
        tags: [ api_platform.filter ]
        autowire: false
        autoconfigure: false
        public: false
