services:
    parent.exists_filter:
        parent: api_platform.doctrine.orm.exists_filter
        arguments: [ { parent: ~ } ]
        tags: [ api_platform.filter ]
        autowire: false
        autoconfigure: false
        public: false

    parent.search_filter:
        parent: api_platform.doctrine.orm.search_filter
        arguments: [ { parent: exact } ]
        tags: [ api_platform.filter ]
        autowire: false
        autoconfigure: false
        public: false
