# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        slider.storage:
            adapter: asyncaws
            visibility: public
            options:
                client: 'digitalocean_spaces_client'
                bucket: '%env(DOS_BUCKET)%'
                prefix: '%uploads.slider%'
        cure.storage:
            adapter: asyncaws
            visibility: public
            options:
                client: 'digitalocean_spaces_client'
                bucket: '%env(DOS_BUCKET)%'
                prefix: '%uploads.cure%'
        customer_comment.storage:
            adapter: asyncaws
            visibility: public
            options:
                client: 'digitalocean_spaces_client'
                bucket: '%env(DOS_BUCKET)%'
                prefix: '%uploads.customer_comment%'
        page.storage:
            adapter: asyncaws
            visibility: public
            options:
                client: 'digitalocean_spaces_client'
                bucket: '%env(DOS_BUCKET)%'
                prefix: '%uploads.page%'
        gallery.storage:
            adapter: asyncaws
            visibility: public
            options:
                client: 'digitalocean_spaces_client'
                bucket: '%env(DOS_BUCKET)%'
                prefix: '%uploads.gallery%'
        doctor.storage:
            adapter: asyncaws
            visibility: public
            options:
                client: 'digitalocean_spaces_client'
                bucket: '%env(DOS_BUCKET)%'
                prefix: '%uploads.doctor%'
        blog_post.storage:
            adapter: asyncaws
            visibility: public
            options:
                client: 'digitalocean_spaces_client'
                bucket: '%env(DOS_BUCKET)%'
                prefix: '%uploads.blog_post%'
        editor.storage:
            adapter: asyncaws
            visibility: public
            options:
                client: 'digitalocean_spaces_client'
                bucket: '%env(DOS_BUCKET)%'
                prefix: '%uploads.editor%'
