security:
    access_decision_manager:
        strategy: unanimous

    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        users:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/_api
            provider: users
            jwt: ~
        admin:
            pattern: ^/admin
            lazy: true
            context: primary_auth
            provider: users
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000
                path: ^/
                always_remember_me: true
            form_login:
                login_path: bigoen_admin.login
                check_path: bigoen_admin.login_check
                success_handler: bigoen_admin.security_handler
                failure_handler: bigoen_admin.security_handler
            logout:
                path: bigoen_admin.logout
                target: bigoen_admin
                invalidate_session: true
            entry_point: bigoen_admin.login_form_authenticator

    access_control:
        - { path: ^/admin/login.*, role: PUBLIC_ACCESS }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/_api, role: PUBLIC_ACCESS }
