version: "3.7"

# Standards.
# build, labels, environment, volumes, ports, others, networks, restart.

# Development environment override
services:
    php:
        volumes:
            - ./:/srv/app:rw,cached
            - ./sdocker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
            # If you develop on Linux, comment out the following volumes to just use bind-mounted project directory from host
            # - ./var:/srv/app/var:rw
        env_file:
            - .env.docker
        environment:
            APP_ENV: dev

    caddy:
        volumes:
            - ./sdocker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
            - ./public:/srv/app/public:ro
        env_file:
            - .env.docker
