imports:
    - { resource: packages/api_platform/filters/ }
    - { resource: parameters.php }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $env: '%env(APP_ENV)%'
            $branchEnv: '%env(BRANCH_ENV)%'
            $defaultLocale: '%kernel.default_locale%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Controller
    App\Controller\:
        resource: '../src/Controller/*'
        tags: ['controller.service_arguments']

    # Event Listeners
    App\EventListener\Doctrine\:
        resource: '../src/EventListener/Doctrine/*'
        tags:
            - { name: 'doctrine.orm.entity_listener' }

    # Event Listener for HttpKernel
    App\EventListener\HttpKernel\ResponseJWTAuthListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response, priority: 10 }

    # Digital Ocean Spaces Service
    digitalocean_spaces_client:
        class: 'AsyncAws\S3\S3Client'
        arguments:
            -  endpoint: '%env(DOS_URL)%'
               accessKeyId: '%env(DOS_KEY)%'
               accessKeySecret: '%env(DOS_SECRET)%'

    # Web Services
    App\WebService\Doktor365Service:
        arguments:
            $apiKey: '%env(DOKTOR_365_API_KEY)%'
